
language: objective-c

before_install:
    - gem install cocoapods --quiet
    - pod --version
    - pod setup
    - pod repo update --silent

script:
    - security default-keychain -s ios-build.keychain
    - security unlock-keychain -p travis ios-build.keychain
    #- pod lib lint
    - xctool -project InstagramKitDemo/InstagramKitDemo.xcodeproj -scheme 'InstagramKitDemo'
