
language: objective-c

before_install:
    - gem install cocoapods --quiet
    - pod --version
    - pod setup
    - pod repo update --silent

script:
    #- pod lib lint
    - xctool -project InstagramKitDemo/InstagramKitDemo.xcodeproj -scheme 'InstagramKitDemo'
