
language: objective-c
# before_install:
#     - pod repo remove master
#     - pod setup
script: xcodebuild test -workspace InstagramKit-Example/InstagramKit-Example.xcworkspace -scheme InstagramKit-Example -sdk iphonesimulator -destination "name=iPhone SE"